<?php
/**
 * Register ACF Fields Programmatically
 */

if (!defined('ABSPATH')) {
    exit;
}

// Register directly on acf/init hook
add_action('acf/init', 'nyc_stem_register_course_fields');

/**
 * Register Course Details field group
 */
function nyc_stem_register_course_fields() {
    // Check if ACF function exists
    if (!function_exists('acf_add_local_field_group')) {
        return;
    }

    acf_add_local_field_group(array(
            'key' => 'group_course_details',
            'title' => 'Course Details',
            'fields' => array(
                // === HERO SECTION ===
                // Hero Stats (Mini stats in left column)
                array(
                    'key' => 'field_hero_stats',
                    'label' => 'Hero Stats (Left Column)',
                    'name' => 'hero_stats',
                    'type' => 'repeater',
                    'instructions' => 'Mini stats displayed in hero section (e.g., "Ages 6-16", "1:4 Ratio")',
                    'required' => 0,
                    'layout' => 'block',
                    'button_label' => 'Add Stat',
                    'max' => 3,
                    'sub_fields' => array(
                        array(
                            'key' => 'field_hero_stat_icon_svg',
                            'label' => 'Icon SVG',
                            'name' => 'icon_svg',
                            'type' => 'textarea',
                            'instructions' => 'Paste SVG code for icon (optional - default icon used if empty)',
                            'required' => 0,
                            'rows' => 3,
                        ),
                        array(
                            'key' => 'field_hero_stat_number',
                            'label' => 'Number/Value',
                            'name' => 'number',
                            'type' => 'text',
                            'instructions' => 'e.g., "Ages 6-16", "1:4"',
                            'required' => 1,
                            'placeholder' => 'Ages 6-16',
                        ),
                        array(
                            'key' => 'field_hero_stat_label',
                            'label' => 'Label',
                            'name' => 'label',
                            'type' => 'text',
                            'instructions' => 'e.g., "Age Range", "Student Ratio"',
                            'required' => 1,
                            'placeholder' => 'Age Range',
                        ),
                    ),
                ),
                // Hero Card Stats (Right column card)
                array(
                    'key' => 'field_hero_card_title',
                    'label' => 'Hero Card Title',
                    'name' => 'hero_card_title',
                    'type' => 'text',
                    'instructions' => 'Title for stats card (default: "Our Track Record")',
                    'required' => 0,
                    'default_value' => 'Our Track Record',
                    'placeholder' => 'Our Track Record',
                ),
                array(
                    'key' => 'field_hero_card_stats',
                    'label' => 'Hero Card Stats',
                    'name' => 'hero_card_stats',
                    'type' => 'repeater',
                    'instructions' => 'Stats for right column card (e.g., "500+ Students", "98% Success Rate")',
                    'required' => 0,
                    'layout' => 'block',
                    'button_label' => 'Add Stat',
                    'max' => 4,
                    'sub_fields' => array(
                        array(
                            'key' => 'field_hero_card_stat_icon_svg',
                            'label' => 'Icon SVG',
                            'name' => 'icon_svg',
                            'type' => 'textarea',
                            'instructions' => 'Paste SVG code for icon (optional - default icon used if empty)',
                            'required' => 0,
                            'rows' => 3,
                        ),
                        array(
                            'key' => 'field_hero_card_stat_number',
                            'label' => 'Number/Value',
                            'name' => 'number',
                            'type' => 'text',
                            'instructions' => 'e.g., "500+", "98%"',
                            'required' => 1,
                            'placeholder' => '500+',
                        ),
                        array(
                            'key' => 'field_hero_card_stat_label',
                            'label' => 'Label',
                            'name' => 'label',
                            'type' => 'text',
                            'instructions' => 'e.g., "Students Served", "Success Rate"',
                            'required' => 1,
                            'placeholder' => 'Students Served',
                        ),
                    ),
                ),

                // === TRUST BAR (Optional) ===
                array(
                    'key' => 'field_trust_bar_items',
                    'label' => 'Trust Bar Items (Optional)',
                    'name' => 'trust_bar_items',
                    'type' => 'repeater',
                    'instructions' => 'Trust indicators displayed below hero (leave empty to hide section)',
                    'required' => 0,
                    'layout' => 'block',
                    'button_label' => 'Add Trust Item',
                    'max' => 4,
                    'sub_fields' => array(
                        array(
                            'key' => 'field_trust_item_icon_svg',
                            'label' => 'Icon SVG',
                            'name' => 'icon_svg',
                            'type' => 'textarea',
                            'instructions' => 'Paste SVG code for icon (optional - shield icon used if empty)',
                            'required' => 0,
                            'rows' => 3,
                        ),
                        array(
                            'key' => 'field_trust_item_text',
                            'label' => 'Text',
                            'name' => 'text',
                            'type' => 'text',
                            'instructions' => 'e.g., "Certified Instructors", "Money-Back Guarantee"',
                            'required' => 1,
                            'placeholder' => 'Certified Instructors',
                        ),
                    ),
                ),

                // === PROGRAM/TIMELINE SECTION ===
                array(
                    'key' => 'field_program_badge',
                    'label' => 'Program Badge',
                    'name' => 'program_badge',
                    'type' => 'text',
                    'instructions' => 'Optional badge above program title (e.g., "OUR CURRICULUM")',
                    'required' => 0,
                    'placeholder' => 'OUR CURRICULUM',
                ),
                array(
                    'key' => 'field_program_title',
                    'label' => 'Program Title',
                    'name' => 'program_title',
                    'type' => 'text',
                    'instructions' => 'Program section title (default: "3-Module Success System")',
                    'required' => 0,
                    'default_value' => '3-Module Success System',
                    'placeholder' => '3-Module Success System',
                ),
                array(
                    'key' => 'field_program_subtitle',
                    'label' => 'Program Subtitle',
                    'name' => 'program_subtitle',
                    'type' => 'text',
                    'instructions' => 'Optional subtitle explaining the program',
                    'required' => 0,
                    'placeholder' => 'A structured approach to mastering...',
                ),
                array(
                    'key' => 'field_program_modules',
                    'label' => 'Program Modules',
                    'name' => 'program_modules',
                    'type' => 'repeater',
                    'instructions' => 'Add program modules (typically 3)',
                    'required' => 0,
                    'layout' => 'block',
                    'button_label' => 'Add Module',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_module_duration',
                            'label' => 'Duration',
                            'name' => 'duration',
                            'type' => 'text',
                            'instructions' => 'e.g., "Weeks 1-4", "Month 1"',
                            'required' => 0,
                            'placeholder' => 'Weeks 1-4',
                        ),
                        array(
                            'key' => 'field_module_title',
                            'label' => 'Module Title',
                            'name' => 'title',
                            'type' => 'text',
                            'instructions' => 'Module headline',
                            'required' => 1,
                            'placeholder' => 'Foundations & Assessment',
                        ),
                        array(
                            'key' => 'field_module_meta',
                            'label' => 'Meta Info',
                            'name' => 'meta',
                            'type' => 'text',
                            'instructions' => 'Optional meta text below title',
                            'required' => 0,
                            'placeholder' => 'Build your foundation',
                        ),
                        array(
                            'key' => 'field_module_description',
                            'label' => 'Description',
                            'name' => 'description',
                            'type' => 'textarea',
                            'instructions' => 'Module description',
                            'required' => 0,
                            'rows' => 3,
                        ),
                        array(
                            'key' => 'field_module_highlights',
                            'label' => 'Highlights',
                            'name' => 'highlights',
                            'type' => 'repeater',
                            'instructions' => 'Key highlights/bullet points',
                            'required' => 0,
                            'layout' => 'table',
                            'button_label' => 'Add Highlight',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_highlight_text',
                                    'label' => 'Text',
                                    'name' => 'text',
                                    'type' => 'text',
                                    'required' => 1,
                                ),
                            ),
                        ),
                    ),
                ),

                // Course Price
                array(
                    'key' => 'field_course_price',
                    'label' => 'Course Price',
                    'name' => 'course_price',
                    'type' => 'text',
                    'instructions' => 'Display price (e.g., "$1,200" or "Contact for pricing")',
                    'required' => 0,
                    'default_value' => '',
                    'placeholder' => '$1,200',
                ),
                // Course Duration
                array(
                    'key' => 'field_course_duration',
                    'label' => 'Course Duration',
                    'name' => 'course_duration',
                    'type' => 'text',
                    'instructions' => 'e.g., "8-12 weeks", "10 sessions", "Summer 2025"',
                    'required' => 0,
                    'default_value' => '',
                    'placeholder' => '8-12 weeks',
                ),
                // Class Format
                array(
                    'key' => 'field_class_format',
                    'label' => 'Class Format',
                    'name' => 'class_format',
                    'type' => 'checkbox',
                    'instructions' => 'Select all formats that apply',
                    'required' => 0,
                    'choices' => array(
                        'private' => 'Private (1-on-1)',
                        'group' => 'Group Classes',
                        'online' => 'Online',
                        'in-person' => 'In-Person',
                    ),
                    'default_value' => array(),
                    'layout' => 'vertical',
                ),
                // Why Choose Us (Repeater) - OPTIONAL OVERRIDE
                array(
                    'key' => 'field_why_choose_us',
                    'label' => 'Why Choose Us (Optional Override)',
                    'name' => 'why_choose_us',
                    'type' => 'repeater',
                    'instructions' => '🌐 OPTIONAL: Leave empty to use default global benefits (Proven Track Record, Comprehensive Curriculum, Small Classes, Digital Ready). Only add custom benefits if this course needs different messaging (e.g., "Convenient Downtown Location" instead of "Digital SHSAT Ready").',
                    'required' => 0,
                    'layout' => 'block',
                    'button_label' => 'Add Custom Benefit',
                    'max' => 4,
                    'sub_fields' => array(
                        array(
                            'key' => 'field_benefit_icon',
                            'label' => 'Icon',
                            'name' => 'icon',
                            'type' => 'text',
                            'instructions' => 'Emoji or icon class (e.g., 🎯 or dashicons-star-filled)',
                            'default_value' => '⭐',
                            'placeholder' => '🎯',
                        ),
                        array(
                            'key' => 'field_benefit_title',
                            'label' => 'Title',
                            'name' => 'title',
                            'type' => 'text',
                            'instructions' => 'Benefit headline',
                            'required' => 1,
                            'placeholder' => 'Expert Instructors',
                        ),
                        array(
                            'key' => 'field_benefit_description',
                            'label' => 'Description',
                            'name' => 'description',
                            'type' => 'textarea',
                            'instructions' => 'Short explanation of this benefit',
                            'required' => 1,
                            'rows' => 3,
                            'placeholder' => 'Learn from experienced educators...',
                        ),
                    ),
                ),
                // === FAQ SECTION ===
                array(
                    'key' => 'field_faq_badge',
                    'label' => 'FAQ Badge',
                    'name' => 'faq_badge',
                    'type' => 'text',
                    'instructions' => 'Optional badge above FAQ title (e.g., "QUESTIONS?")',
                    'required' => 0,
                    'placeholder' => 'QUESTIONS?',
                ),
                array(
                    'key' => 'field_faq_title',
                    'label' => 'FAQ Title',
                    'name' => 'faq_title',
                    'type' => 'text',
                    'instructions' => 'FAQ section title (default: "Frequently Asked Questions")',
                    'required' => 0,
                    'default_value' => 'Frequently Asked Questions',
                    'placeholder' => 'Frequently Asked Questions',
                ),
                array(
                    'key' => 'field_faq_subtitle',
                    'label' => 'FAQ Subtitle',
                    'name' => 'faq_subtitle',
                    'type' => 'text',
                    'instructions' => 'Optional subtitle for FAQ section',
                    'required' => 0,
                    'placeholder' => 'Everything you need to know about...',
                ),
                // FAQs (Repeater)
                array(
                    'key' => 'field_course_faqs',
                    'label' => 'FAQs',
                    'name' => 'course_faqs',
                    'type' => 'repeater',
                    'instructions' => 'Add frequently asked questions',
                    'required' => 0,
                    'layout' => 'block',
                    'button_label' => 'Add FAQ',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_faq_question',
                            'label' => 'Question',
                            'name' => 'question',
                            'type' => 'text',
                            'instructions' => 'FAQ question',
                            'required' => 1,
                            'placeholder' => 'What is included in the course?',
                        ),
                        array(
                            'key' => 'field_faq_answer',
                            'label' => 'Answer',
                            'name' => 'answer',
                            'type' => 'wysiwyg',
                            'instructions' => 'FAQ answer with formatting',
                            'required' => 1,
                            'toolbar' => 'basic',
                            'media_upload' => 0,
                        ),
                    ),
                ),
                array(
                    'key' => 'field_faq_footer_text',
                    'label' => 'FAQ Footer Text',
                    'name' => 'faq_footer_text',
                    'type' => 'text',
                    'instructions' => 'Optional text below FAQs (e.g., "Still have questions?")',
                    'required' => 0,
                    'placeholder' => 'Still have questions?',
                ),
                array(
                    'key' => 'field_faq_link_url',
                    'label' => 'FAQ Link URL',
                    'name' => 'faq_link_url',
                    'type' => 'url',
                    'instructions' => 'Optional link to full FAQ page',
                    'required' => 0,
                    'placeholder' => 'https://example.com/faqs',
                ),
                array(
                    'key' => 'field_faq_link_text',
                    'label' => 'FAQ Link Text',
                    'name' => 'faq_link_text',
                    'type' => 'text',
                    'instructions' => 'Link text (default: "View All FAQs")',
                    'required' => 0,
                    'default_value' => 'View All FAQs',
                    'placeholder' => 'View All FAQs',
                ),

                // === CTA SECTION ===
                array(
                    'key' => 'field_cta_badge',
                    'label' => 'CTA Badge',
                    'name' => 'cta_badge',
                    'type' => 'text',
                    'instructions' => 'Optional badge above CTA title',
                    'required' => 0,
                    'placeholder' => 'GET STARTED',
                ),
                array(
                    'key' => 'field_cta_title',
                    'label' => 'CTA Title',
                    'name' => 'cta_title',
                    'type' => 'text',
                    'instructions' => 'CTA section title (default: "Ready to Begin Your Journey?")',
                    'required' => 0,
                    'default_value' => 'Ready to Begin Your Journey?',
                    'placeholder' => 'Ready to Begin Your Journey?',
                ),
                array(
                    'key' => 'field_cta_subtitle',
                    'label' => 'CTA Subtitle',
                    'name' => 'cta_subtitle',
                    'type' => 'text',
                    'instructions' => 'Optional subtitle for CTA section',
                    'required' => 0,
                    'placeholder' => 'Join hundreds of students who have...',
                ),
                array(
                    'key' => 'field_cta_button_text',
                    'label' => 'CTA Button Text',
                    'name' => 'cta_button_text',
                    'type' => 'text',
                    'instructions' => 'Optional custom button text (uses Inquiry Button Settings if empty)',
                    'required' => 0,
                    'placeholder' => 'Inquire Now',
                ),
                array(
                    'key' => 'field_cta_button_url',
                    'label' => 'CTA Button URL',
                    'name' => 'cta_button_url',
                    'type' => 'url',
                    'instructions' => 'Optional custom button URL (uses Inquiry Button Settings if empty)',
                    'required' => 0,
                    'placeholder' => 'https://example.com/enroll',
                ),
                // Testimonials (Repeater)
                array(
                    'key' => 'field_testimonials',
                    'label' => 'Testimonials',
                    'name' => 'testimonials',
                    'type' => 'repeater',
                    'instructions' => 'Add student testimonials (optional)',
                    'required' => 0,
                    'layout' => 'block',
                    'button_label' => 'Add Testimonial',
                    'max' => 6,
                    'sub_fields' => array(
                        array(
                            'key' => 'field_testimonial_name',
                            'label' => 'Student Name',
                            'name' => 'student_name',
                            'type' => 'text',
                            'instructions' => 'Student or parent name',
                            'required' => 1,
                            'placeholder' => 'Sarah M.',
                        ),
                        array(
                            'key' => 'field_testimonial_quote',
                            'label' => 'Quote',
                            'name' => 'quote',
                            'type' => 'textarea',
                            'instructions' => 'Testimonial text',
                            'required' => 1,
                            'rows' => 4,
                            'placeholder' => 'This program changed my test scores...',
                        ),
                        array(
                            'key' => 'field_testimonial_photo',
                            'label' => 'Photo',
                            'name' => 'photo',
                            'type' => 'image',
                            'instructions' => 'Student photo (optional, 200x200px recommended)',
                            'required' => 0,
                            'return_format' => 'array',
                            'preview_size' => 'thumbnail',
                        ),
                    ),
                ),
                // Schedule Information
                array(
                    'key' => 'field_schedule_info',
                    'label' => 'Schedule Information',
                    'name' => 'schedule_info',
                    'type' => 'wysiwyg',
                    'instructions' => 'Add course dates, times, calendar info (optional)',
                    'required' => 0,
                    'toolbar' => 'full',
                    'media_upload' => 1,
                ),
                // Inquiry Button Settings (Group) - GLOBAL
                array(
                    'key' => 'field_inquiry_settings',
                    'label' => 'Inquiry Button Settings (GLOBAL)',
                    'name' => 'inquiry_settings',
                    'type' => 'group',
                    'instructions' => '🌐 GLOBAL SETTINGS: Leave these empty to use site-wide defaults. The button will automatically link to /student-enrollment/ with the course name in the URL.',
                    'layout' => 'block',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_inquiry_button_text',
                            'label' => 'Button Text (Optional Override)',
                            'name' => 'inquiry_button_text',
                            'type' => 'text',
                            'instructions' => 'Leave empty to use default "Inquire Now". Only customize if this specific course needs different text.',
                            'default_value' => '',
                            'placeholder' => 'Inquire Now',
                        ),
                        array(
                            'key' => 'field_custom_inquiry_url',
                            'label' => 'Custom URL (Optional Override)',
                            'name' => 'custom_inquiry_url',
                            'type' => 'url',
                            'instructions' => 'Leave empty to use default /student-enrollment/. Only customize if this specific course needs a different URL.',
                            'required' => 0,
                            'placeholder' => 'https://nycstemclub.local/student-enrollment/',
                        ),
                    ),
                ),
                // Related Courses
                array(
                    'key' => 'field_related_courses',
                    'label' => 'Related Courses',
                    'name' => 'related_courses',
                    'type' => 'post_object',
                    'instructions' => 'Select 2-4 related courses to display',
                    'required' => 0,
                    'post_type' => array('course'),
                    'allow_null' => 1,
                    'multiple' => 1,
                    'return_format' => 'object',
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'course',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
        ));
}
